Date::DATE_FORMATS[:date] = '%-m/%d'
Date::DATE_FORMATS[:year_month] = '%Y年%-m月'
Date::DATE_FORMATS[:month] = '%-m月'
Time::DATE_FORMATS[:hour] = '%H'
Time::DATE_FORMATS[:min] = '%M'
Time::DATE_FORMATS[:hourmin] = '%H%M'